<?xml version="1.0" encoding="utf-8"?><Database Name="QuikGrub" Class="GrubDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=budohacks.database.windows.net;Initial Catalog=QuikGrub;User ID=budocf" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuikGrubConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.company_info" Member="company_infos">
    <Type Name="company_info">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="delivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="orders" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_first" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="owner_last" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_contact_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_contact_phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="payment_status" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.orders" Member="orders">
    <Type Name="order">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="order_placed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="special_needs" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="customer_location" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fulfilled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.company_login" Member="company_logins">
    <Type Name="company_login">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.customer_info" Member="customer_infos">
    <Type Name="customer_info">
      <Column Name="name_first" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name_last" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.customer_login" Member="customer_logins">
    <Type Name="customer_login">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="menu_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="allergy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.menu" Member="menus">
    <Type Name="menu">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.create_company_info" Method="create_company_info">
    <Parameter Name="delivery" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="location" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="orders" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="owner_first" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="owner_last" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone_number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="point_of_contact_email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="point_of_contact_phone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="payment_status" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_company_info" Method="update_company_info">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="delivery" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="location" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="orders" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="owner_first" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="owner_last" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone_number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="point_of_contact_email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="point_of_contact_phone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="payment_status" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_company_login" Method="create_company_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="hashed_password" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_customer_info" Method="create_customer_info">
    <Parameter Name="name_first" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="name_last" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_customer_login" Method="create_customer_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="hashed_password" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_item" Method="create_item">
    <Parameter Name="menu_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="about" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="allergy" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_menu" Method="create_menu">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="about" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="start_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="end_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="parent_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="company_id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_order_items" Method="create_order_items">
    <Parameter Name="order_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="item_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="notes" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.create_orders" Method="create_orders">
    <Parameter Name="customer_id" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="company_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="order_placed" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="special_needs" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="customer_location" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="fulfilled" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_email_with_username_company" Method="get_email_with_username_company">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="get_email_with_username_companyResult">
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_email_with_username_customer" Method="get_email_with_username_customer">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="get_email_with_username_customerResult">
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_items_with_company_id" Method="get_items_with_company_id">
    <Parameter Name="company_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="item_name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="get_items_with_company_idResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="id1" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="menu_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about1" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="allergy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ProcedureName" Method="ProcedureName">
    <ElementType Name="ProcedureNameResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_with_id_order_items" Method="select_with_id_order_items">
    <Parameter Name="order_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="item_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="select_with_id_order_itemsResult">
      <Column Name="order_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="item_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_company_info" Method="selectall_company_info">
    <ElementType Name="selectall_company_infoResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="delivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="orders" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_first" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="owner_last" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_contact_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_contact_phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="payment_status" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_company_login" Method="selectall_company_login">
    <ElementType Name="selectall_company_loginResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_customer_info" Method="selectall_customer_info">
    <ElementType Name="selectall_customer_infoResult">
      <Column Name="name_first" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name_last" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_customer_login" Method="selectall_customer_login">
    <ElementType Name="selectall_customer_loginResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_item" Method="selectall_item">
    <ElementType Name="selectall_itemResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="menu_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="allergy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_menu" Method="selectall_menu">
    <ElementType Name="selectall_menuResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_order_items" Method="selectall_order_items">
    <ElementType Name="selectall_order_itemsResult">
      <Column Name="order_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="item_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_with_id_company_info" Method="selectall_with_id_company_info">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="selectall_with_id_company_infoResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="delivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="orders" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="owner_first" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="owner_last" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_contact_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_contact_phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="payment_status" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_with_id_item" Method="selectall_with_id_item">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="selectall_with_id_itemResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="menu_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="allergy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_with_id_menu" Method="selectall_with_id_menu">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="selectall_with_id_menuResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_with_username_company_login" Method="selectall_with_username_company_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="selectall_with_username_company_loginResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_with_username_customer_info" Method="selectall_with_username_customer_info">
    <Parameter Name="username" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="selectall_with_username_customer_infoResult">
      <Column Name="name_first" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name_last" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectall_with_username_customer_login" Method="selectall_with_username_customer_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="selectall_with_username_customer_loginResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hashed_password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>